### ISSUE TITLE
"Switch" not properly working

### ISSUE THREAD

**Issue by Radiation-Transport** [dodu94/JADE#142]
Problem in the usage of the switch utilities with this very easy input.
<img width="223" alt="image" src="https://user-images.githubusercontent.com/48320561/150766918-10a3322e-69b4-4ed4-84bf-c929bfa6dad3.png">

File here --> [Material.txt](https://github.com/dodu94/JADE/files/7924802/Material.txt)

**Comment by dodu94** [comment]
Can you better clarify what is the issue? e.g. which kind of fraction were you attempt to obtain? what is the expexted result versus obtained result, etc.

**Comment by Radiation-Transport** [comment]
The material was not read correctly because the space before the ZAID were too few. Changing that it works ok.

**Comment by dodu94** [comment]
this is a known issue and if I remember correctly it comes from numjuggler parsing. I always thought that the reason is that the spacing number is the minimum possible for the input to run correctly in MCNP. If that is not the case an issue should be raised to numjuggler
