### ISSUE TITLE
Dedicated test on utilities using PNNL material handbook

### ISSUE THREAD

**Issue by Radiation-Transport** [dodu94/JADE#147]
Insert dedicated test on material utilities (i.e., switching material wgt fraction to atomic fraction and vice versa) using PNNL material handbook, which can be find [here](https://www.pnnl.gov/publications/compendium-material-composition-data-radiation-transport-modeling-1)

**Comment by dodu94** [comment]
a test has been added to the suite on Bismuth Germanate and the differences between JADE code and pnnl are within the tolerance of 1e-5.
