### ISSUE TITLE
Uniform the libraries colors in the Sphere Leakage ATLAS plots

### ISSUE THREAD

**Issue by Radiation-Transport** [dodu94/JADE#155]
JEFF-3.3 pink than green. It is proposed to be a unique color among the different isotopes.
![image](https://user-images.githubusercontent.com/48320561/165541417-5760715a-8b80-4a19-a60c-ab3c8a9f7f8e.png)

**Comment by dodu94** [comment]
Colors are drafted from a sequence, if less libraries are present for a specific isotope the colors will change. Assigning a priori the color to a library would mean to move some logic from the plotter to the assessment and it is not recommended.
